mainnet:
  oracle_registry: '0x75fBFe26B21fd3EA008af0C764949f8214150C8f'
  cdp_registry: '0x1a5Ff58BC3246Eb233fEA20D32b79B5F01eC650c'
  vault: '0xb1cFF81b9305166ff1EFc49A129ad2AfCd7BCf19'
  vault_manager_parameters: '0x203153522B9EAef4aE17c6e99851EE7b2F7D312E'
  vault_parameters: '0xB46F8CF42e504Efe8BEf895f848741daA55e9f1D'
  sushiswap_factory: '0xC0AEe478e3658e2610c5F7A4A2E1777cE9e4f2Ac'
  uniswap_factory: '0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f'
  sushiswap_init_code_hash: '0xe18a34eb0e04b04f7a0ac29a6e80748dca96319b42c54d679cb821dca90c6303'
  eth_usd_aggregator: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
  weth: '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2'
  old_col_mock: '0x6aade8a8a6b85921009d2caa25dc69348f4c009e'
  vault_managers:
    - address: '0x7f50d78062304B6f523f20E9bACa8F3C72197424'
      liquidationTrigger: '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
      fromBlock: 11316117
      toBlock: 11351816
      col: true
    - address: '0x78727A77028d9130D2772713d570780231E64ECf'
      liquidationTrigger: '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
      fromBlock: 11354460
      toBlock: 11378571
      col: true
    - address: '0x754106b2f312c987Dd34161F8b4735392fa93F06'
      liquidationTrigger: '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
      fromBlock: 11320948
      toBlock: 11329829
      col: true
    - address: '0x3052764f1af2f8B7a887dEAfA42153530676079B'
      liquidationTrigger: '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
      fromBlock: 11373663
      toBlock: 12072495
      col: true
    - address: '0x211a6d4d4f49c0c5814451589d6378fda614adb9'
      liquidationTrigger: '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
      fromBlock: 11373662
      toBlock: 12198630
      col: true
    - address: '0x2637D65912660e527C998824b8933d1A1bD7daA3'
      liquidationTrigger: '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
      fromBlock: 12101566
      toBlock: 12198630
    - address: '0x54ba276a62e7e3e76d362f672f00ed31a983067b'
      liquidationTrigger: '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
      fromBlock: 11609549
      toBlock: 12198630
    - address: '0xD90332DB0FE0e5eA1A195A5Ba6fc8949EaB8AB4E'
      liquidationTrigger: '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
      fromBlock: 11610755
      toBlock: 12058830
    - address: '0x18A2381d318EE56D19316f4a7D39a2a7996e8390'
      liquidationTrigger: '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
      fromBlock: 12101763
      toBlock: 12198630
    - address: '0xB82c6D510B3a0Dc9f198dE0ad2a3839973c6783c'
      liquidationTrigger: '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
      fromBlock: 11888275
      toBlock: 12198630
    - address: '0x7a646c42b64d21E6b871EfD85f54d707aCe1f9D1'
      liquidationTrigger: '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
      fromBlock: 12070783
      toBlock: 12198630
    - address: '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
      liquidationTrigger: '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
      fromBlock: 12198630
    - address: '0xad3617d11f4c1d30603551ea75e9ace9cb386e15'
      liquidationTrigger: '0xad3617d11f4c1d30603551ea75e9ace9cb386e15'
      fromBlock: 12258922
  liquidation_triggers:
    - '0x0e13ab042eC5AB9Fc6F43979406088B9028F66fA'
    - '0xad3617d11f4c1d30603551ea75e9ace9cb386e15'
  new_version_of_liquidation_trigger:
    '0x78d09b58402c29016425497289e12fdd12f06027': '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
    '0x0ca1a59a987922375234df94919a456f61e93e1e': '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
    '0x989ac9c8353c3f01412705d7e50b4ab9e804c227': '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
    '0xfeacfc01e122bb6b17dc4aef4f0e3be20fca888d': '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
    '0x20c854cdd322d3a501da91374027b4b257de57dd': '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
    '0x88f2ec209b58076db31e4221a737313941be2ef8': '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
    '0xb088c78a8e2e454a6145bfba37ca5de129688ff7': '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
    '0x97d940afe6cb90bea9e7562d8f3fdc1fc3e691f4': '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
    '0xad3617d11f4c1d30603551ea75e9ace9cb386e15': '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
  auctions:
    - '0xaef1ed4c492bf4c57221be0706def67813d79955'
  fallback_liquidation_trigger: '0xad3617d11f4c1d30603551ea75e9ace9cb386e15'
  crv3_representations:
    - '0x4bfb2fa13097e5312b19585042fdbf3562dc8676'
    - '0x6c3f90f043a72fa612cbac8115ee7e52bde6e490'
  tri_pool: '0xbebc44782c7db0a1a60cb6fe97d0b483032ff1c7'
bsc:
  oracle_registry: '0xbea721ACe12e881cb44Dbe9361ffEd9141CE547F'
  cdp_registry: '0xE8372dcef80189c0F88631507f6466b3f60E24A4'
  vault: '0xdacfeed000e12c356fb72ab5089e7dd80ff4dd93'
  vault_manager_parameters: '0x99f2B13C28A4183a5d5e0fe02B1B5aeEe85FAF5A'
  vault_parameters: '0x56c7CA666d192332F72a5842E72eED5f59F0fb48'
  sushiswap_factory: '0xcA143Ce32Fe78f1f7019d7d551a6402fC5350c73'
  uniswap_factory: ''
  sushiswap_init_code_hash: '0x00fb7f630766e6a796048ea87d01acd3068e8ff67d078148a3fa3f4a84f69bd5'
  eth_usd_aggregator: '0x0567F2323251f0Aab15c8dFb1967E4e8A7D42aeE'
  weth: '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c'
  old_col_mock: ''
  vault_managers:
    - address: '0x7f50d78062304B6f523f20E9bACa8F3C72197424'
      liquidationTrigger: '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
      fromBlock: 11316117
      toBlock: 11351816
      col: true
    - address: '0x78727A77028d9130D2772713d570780231E64ECf'
      liquidationTrigger: '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
      fromBlock: 11354460
      toBlock: 11378571
      col: true
    - address: '0x754106b2f312c987Dd34161F8b4735392fa93F06'
      liquidationTrigger: '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
      fromBlock: 11320948
      toBlock: 11329829
      col: true
    - address: '0x3052764f1af2f8B7a887dEAfA42153530676079B'
      liquidationTrigger: '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
      fromBlock: 11373663
      toBlock: 12072495
      col: true
    - address: '0x211a6d4d4f49c0c5814451589d6378fda614adb9'
      liquidationTrigger: '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
      fromBlock: 11373662
      toBlock: 12198630
      col: true
    - address: '0x2637D65912660e527C998824b8933d1A1bD7daA3'
      liquidationTrigger: '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
      fromBlock: 12101566
      toBlock: 12198630
    - address: '0x54ba276a62e7e3e76d362f672f00ed31a983067b'
      liquidationTrigger: '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
      fromBlock: 11609549
      toBlock: 12198630
    - address: '0xD90332DB0FE0e5eA1A195A5Ba6fc8949EaB8AB4E'
      liquidationTrigger: '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
      fromBlock: 11610755
      toBlock: 12058830
    - address: '0x18A2381d318EE56D19316f4a7D39a2a7996e8390'
      liquidationTrigger: '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
      fromBlock: 12101763
      toBlock: 12198630
    - address: '0xB82c6D510B3a0Dc9f198dE0ad2a3839973c6783c'
      liquidationTrigger: '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
      fromBlock: 11888275
      toBlock: 12198630
    - address: '0x7a646c42b64d21E6b871EfD85f54d707aCe1f9D1'
      liquidationTrigger: '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
      fromBlock: 12070783
      toBlock: 12198630
    - address: '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
      liquidationTrigger: '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
      fromBlock: 12198630
    - address: '0xad3617d11f4c1d30603551ea75e9ace9cb386e15'
      liquidationTrigger: '0xad3617d11f4c1d30603551ea75e9ace9cb386e15'
      fromBlock: 12258922
    liquidation_triggers:
      - '0x0e13ab042eC5AB9Fc6F43979406088B9028F66fA'
      - '0xad3617d11f4c1d30603551ea75e9ace9cb386e15'
    new_version_of_liquidation_trigger:
      '0x78d09b58402c29016425497289e12fdd12f06027': '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
      '0x0ca1a59a987922375234df94919a456f61e93e1e': '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
      '0x989ac9c8353c3f01412705d7e50b4ab9e804c227': '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
      '0xfeacfc01e122bb6b17dc4aef4f0e3be20fca888d': '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
      '0x20c854cdd322d3a501da91374027b4b257de57dd': '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
      '0x88f2ec209b58076db31e4221a737313941be2ef8': '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
      '0xb088c78a8e2e454a6145bfba37ca5de129688ff7': '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
      '0x97d940afe6cb90bea9e7562d8f3fdc1fc3e691f4': '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
      '0xad3617d11f4c1d30603551ea75e9ace9cb386e15': '0x0e13ab042ec5ab9fc6f43979406088b9028f66fa'
    auctions:
      - '0xaef1ed4c492bf4c57221be0706def67813d79955'
    fallback_liquidation_trigger: '0xad3617d11f4c1d30603551ea75e9ace9cb386e15'
    crv3_representations:
      - '0x4bfb2fa13097e5312b19585042fdbf3562dc8676'
      - '0x6c3f90f043a72fa612cbac8115ee7e52bde6e490'
    tri_pool: '0xbebc44782c7db0a1a60cb6fe97d0b483032ff1c7'
