mainnet:
  explorer_url: 'https://etherscan.io'
  liquidation_url: 'https://liquidation.unit.xyz'
  chain_id: 1
  hash_tag_prefix: ''
  main_symbol: 'ETH'
  oracle_registry: '0x75fBFe26B21fd3EA008af0C764949f8214150C8f'
  cdp_registry: '0x1a5Ff58BC3246Eb233fEA20D32b79B5F01eC650c'
  vault: '0xb1cFF81b9305166ff1EFc49A129ad2AfCd7BCf19'
  vault_manager_parameters: '0x203153522B9EAef4aE17c6e99851EE7b2F7D312E'
  vault_parameters: '0xB46F8CF42e504Efe8BEf895f848741daA55e9f1D'

  uniswap_factory: '0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f'

  sushiswap_factory: '0xC0AEe478e3658e2610c5F7A4A2E1777cE9e4f2Ac'
  sushiswap_init_code_hash: '0xe18a34eb0e04b04f7a0ac29a6e80748dca96319b42c54d679cb821dca90c6303'

  shibaswap_factory: '0x115934131916c8b277dd010ee02de363c09d037c'
  shibaswap_init_code_hash: '0x65d1a3b1e46c6e4f1be1ad5f99ef14dc488ae0549dc97db9b30afe2241ce1c7a'

  eth_usd_aggregator: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
  weth: '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2'
  vault_managers:
    - '0xee84f58ee39c6122c76c1fa54f0b6f33da1642ec'
    - '0x3bb1c7dfd879c1e21d28e3b18189463c375c9679'
  auctions:
    - '0xaef1ed4c492bf4c57221be0706def67813d79955'
  fallback_liquidation_trigger: '0x3bb1c7dfd879c1e21d28e3b18189463c375c9679'
  main_liquidation_trigger: '0xee84f58ee39c6122c76c1fa54f0b6f33da1642ec'
  crv3_representations:
    - '0x4bfb2fa13097e5312b19585042fdbf3562dc8676'
  crv3: '0x6c3f90f043a72fa612cbac8115ee7e52bde6e490'
  liquidation_check_timeout: 10
  liquidation_confirmations_threshold: 3
  curve_provider: '0x0000000022D53366457F9d5E68Ec105046FC4383'
  liquidation_debt_threshold: 200
  liquidation_debt_threshold_keydonix: 400
bsc:
  explorer_url: 'https://bscscan.com'
  liquidation_url: 'https://bsc.liquidation.unit.xyz'
  chain_id: 56
  hash_tag_prefix: 'bsc_'
  main_symbol: 'BSC'
  oracle_registry: '0xbea721ACe12e881cb44Dbe9361ffEd9141CE547F'
  cdp_registry: '0xE8372dcef80189c0F88631507f6466b3f60E24A4'
  vault: '0xdacfeed000e12c356fb72ab5089e7dd80ff4dd93'
  vault_manager_parameters: '0x99f2B13C28A4183a5d5e0fe02B1B5aeEe85FAF5A'
  vault_parameters: '0x56c7CA666d192332F72a5842E72eED5f59F0fb48'
  sushiswap_factory: '0xcA143Ce32Fe78f1f7019d7d551a6402fC5350c73'
  uniswap_factory: ''
  sushiswap_init_code_hash: '0x00fb7f630766e6a796048ea87d01acd3068e8ff67d078148a3fa3f4a84f69bd5'
  eth_usd_aggregator: '0x0567F2323251f0Aab15c8dFb1967E4e8A7D42aeE'
  weth: '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c'
  vault_managers:
    - '0x1337dac01fc21fa21d17914f96725f7a7b73868f'
  auctions:
    - '0x852de08f3cD5b92dD8b3B92b321363D04EeEc39E'
  fallback_liquidation_trigger: ''
  main_liquidation_trigger: '0x1337dac01fc21fa21d17914f96725f7a7b73868f'
  crv3_representations: ''
  crv3: ''
  liquidation_check_timeout: 100
  liquidation_confirmations_threshold: 3
  curve_provider: ''
  liquidation_debt_threshold: 2
  liquidation_debt_threshold_keydonix: 2
fantom:
  explorer_url: 'https://ftmscan.com'
  liquidation_url: 'https://ftm.liquidation.unit.xyz'
  chain_id: 250
  hash_tag_prefix: 'ftm_'
  main_symbol: 'FTM'
  oracle_registry: '0x0058aB54d4405D8084e8D71B8AB36B3091b21c7D'
  cdp_registry: '0x1442bC024a92C2F96c3c1D2E9274bC4d8119d97e'
  vault: '0xD7A9b0D75e51bfB91c843b23FB2C19aa3B8D958e'
  vault_manager_parameters: '0x1c7aEA8B6498F0854D1fCE542a27ed6a10D71d2f'
  vault_parameters: '0xa8F0b5758041158Cf0375b7AdC8AC175ff031B6C'
  sushiswap_factory: ''
  uniswap_factory: ''
  sushiswap_init_code_hash: ''
  eth_usd_aggregator: '0xf4766552D15AE4d256Ad41B6cf2933482B0680dc'
  weth: '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83'
  vault_managers:
    - '0xD12d6082811709287AE8b6d899Ab841659075FC3'
  auctions:
    - '0x1F18FAc6A422cF4a8D18369F017a100C77b49DeF'
  fallback_liquidation_trigger: ''
  main_liquidation_trigger: '0xD12d6082811709287AE8b6d899Ab841659075FC3'
  crv3_representations: ''
  crv3: ''
  liquidation_check_timeout: 100
  liquidation_confirmations_threshold: 3
  curve_provider: ''
  liquidation_debt_threshold: 2
  liquidation_debt_threshold_keydonix: 2
